"""Software-defined asset definitions for the Security Analytics pipeline.

Defines the complete asset graph from data generation through ML anomaly detection.
Each asset represents a logical data artifact in the pipeline.

Requirements: 8.2, 8.3, 8.8
"""

import subprocess
from pathlib import Path

from dagster import (
    AssetExecutionContext,
    AssetIn,
    MetadataValue,
    Output,
    asset,
)

from scripts.logging_config import get_logger

logger = get_logger("dagster_assets")

# ---------------------------------------------------------------------------
# Ingestion Group
# ---------------------------------------------------------------------------


@asset(
    description="Raw security events generated by Mock Data Generator",
    group_name="ingestion",
    metadata={
        "format": "JSONL + Parquet",
        "output_dir": "mock_data/",
    },
)
def raw_security_events(context: AssetExecutionContext) -> Output[str]:
    """Generate mock security data and return path to output files."""
    from mock_data.generator import GeneratorConfig, generate_security_events, write_events

    config = GeneratorConfig(count=10_000, seed=42)
    context.log.info(f"Generating {config.count} security events with seed={config.seed}")

    events = generate_security_events(config)
    output_paths = write_events(events, config)

    output_dir = str(config.output_dir)
    context.log.info(
        f"Generated {len(events)} events to {output_dir}",
    )

    return Output(
        output_dir,
        metadata={
            "event_count": MetadataValue.int(len(events)),
            "output_dir": MetadataValue.text(output_dir),
            "formats": MetadataValue.text(", ".join(config.output_formats)),
        },
    )


@asset(
    ins={"raw_data": AssetIn("raw_security_events")},
    description="Bronze layer: raw events loaded via DLT pipeline",
    group_name="ingestion",
    metadata={
        "table": "raw_security_events",
        "layer": "bronze",
    },
)
def bronze_events(context: AssetExecutionContext, raw_data: str) -> Output[int]:
    """Run DLT ingestion pipeline. Returns record count."""
    from dlt_pipeline.pipeline import run_ingestion

    source_dir = Path(raw_data)
    context.log.info(f"Running DLT ingestion from {source_dir}")

    result = run_ingestion(source_dir=source_dir)

    context.log.info(
        f"Ingested {result.records_ingested} records, "
        f"rejected {result.records_rejected}, "
        f"batch_id={result.batch_id}"
    )

    return Output(
        result.records_ingested,
        metadata={
            "records_ingested": MetadataValue.int(result.records_ingested),
            "records_rejected": MetadataValue.int(result.records_rejected),
            "elapsed_seconds": MetadataValue.float(result.elapsed_seconds),
            "records_per_second": MetadataValue.float(result.records_per_second),
            "batch_id": MetadataValue.text(result.batch_id),
        },
    )


# ---------------------------------------------------------------------------
# Transformation Group
# ---------------------------------------------------------------------------


@asset(
    ins={"bronze": AssetIn("bronze_events")},
    description="Silver layer: cleaned, deduplicated, enriched events",
    group_name="transformation",
    metadata={
        "table": "silver_events",
        "layer": "silver",
    },
)
def silver_events(context: AssetExecutionContext, bronze: int) -> Output[int]:
    """Run dbt Silver models. Returns record count."""
    context.log.info(f"Running dbt Silver models (bronze has {bronze} records)")

    result = subprocess.run(
        [
            "dbt", "run",
            "--select", "stg_security_events silver_events",
            "--project-dir", "dbt_project",
            "--profiles-dir", "dbt_project",
            "--target", "dev",
        ],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        context.log.error(f"dbt Silver run failed: {result.stderr}")
        raise RuntimeError(f"dbt Silver models failed: {result.stderr}")

    context.log.info("dbt Silver models completed successfully")

    # Count silver records
    import duckdb

    conn = duckdb.connect("data/security_analytics.duckdb", read_only=True)
    try:
        row = conn.execute(
            "SELECT COUNT(*) FROM security_analytics.silver_events"
        ).fetchone()
        record_count = row[0] if row else 0
    except Exception:
        record_count = 0
    finally:
        conn.close()

    return Output(
        record_count,
        metadata={
            "record_count": MetadataValue.int(record_count),
            "dbt_output": MetadataValue.text(result.stdout[-2000:] if result.stdout else ""),
        },
    )


# ---------------------------------------------------------------------------
# Analytics Group
# ---------------------------------------------------------------------------


@asset(
    ins={"silver": AssetIn("silver_events")},
    description="Gold KPI summary table",
    group_name="analytics",
    metadata={
        "table": "kpi_summary",
        "layer": "gold",
    },
)
def gold_kpi_summary(context: AssetExecutionContext, silver: int) -> Output[dict]:
    """Run dbt Gold KPI model. Returns KPI values."""
    context.log.info(f"Running dbt Gold KPI model (silver has {silver} records)")

    result = subprocess.run(
        [
            "dbt", "run",
            "--select", "kpi_summary",
            "--project-dir", "dbt_project",
            "--profiles-dir", "dbt_project",
            "--target", "dev",
        ],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        context.log.error(f"dbt Gold KPI run failed: {result.stderr}")
        raise RuntimeError(f"dbt Gold KPI model failed: {result.stderr}")

    # Read KPI values
    import duckdb

    conn = duckdb.connect("data/security_analytics.duckdb", read_only=True)
    try:
        row = conn.execute(
            "SELECT total_attacks, failed_login_rate, avg_mttd_minutes, "
            "avg_mttr_minutes, sla_compliance FROM security_analytics.kpi_summary"
        ).fetchone()
        kpis = {
            "total_attacks": row[0] if row else 0,
            "failed_login_rate": row[1] if row else 0.0,
            "avg_mttd_minutes": row[2] if row else 0.0,
            "avg_mttr_minutes": row[3] if row else 0.0,
            "sla_compliance": row[4] if row else 0.0,
        }
    except Exception:
        kpis = {}
    finally:
        conn.close()

    context.log.info(f"Gold KPI summary computed: {kpis}")

    return Output(
        kpis,
        metadata={
            "total_attacks": MetadataValue.int(kpis.get("total_attacks", 0)),
            "failed_login_rate": MetadataValue.float(kpis.get("failed_login_rate", 0.0)),
            "avg_mttd_minutes": MetadataValue.float(kpis.get("avg_mttd_minutes", 0.0)),
            "avg_mttr_minutes": MetadataValue.float(kpis.get("avg_mttr_minutes", 0.0)),
            "sla_compliance": MetadataValue.float(kpis.get("sla_compliance", 0.0)),
        },
    )


@asset(
    ins={"silver": AssetIn("silver_events")},
    description="Gold attack volume by day aggregation",
    group_name="analytics",
    metadata={
        "table": "attack_volume_by_day",
        "layer": "gold",
    },
)
def gold_attack_by_day(context: AssetExecutionContext, silver: int) -> Output[int]:
    """Run dbt Gold attack by day model. Returns row count."""
    context.log.info("Running dbt Gold attack_volume_by_day model")

    result = subprocess.run(
        [
            "dbt", "run",
            "--select", "attack_volume_by_day",
            "--project-dir", "dbt_project",
            "--profiles-dir", "dbt_project",
            "--target", "dev",
        ],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        context.log.error(f"dbt Gold attack_by_day run failed: {result.stderr}")
        raise RuntimeError(f"dbt Gold attack_volume_by_day model failed: {result.stderr}")

    # Count rows
    import duckdb

    conn = duckdb.connect("data/security_analytics.duckdb", read_only=True)
    try:
        row = conn.execute(
            "SELECT COUNT(*) FROM security_analytics.attack_volume_by_day"
        ).fetchone()
        row_count = row[0] if row else 0
    except Exception:
        row_count = 0
    finally:
        conn.close()

    return Output(
        row_count,
        metadata={"row_count": MetadataValue.int(row_count)},
    )


@asset(
    ins={"silver": AssetIn("silver_events")},
    description="Gold attack volume by country aggregation",
    group_name="analytics",
    metadata={
        "table": "attack_volume_by_country",
        "layer": "gold",
    },
)
def gold_attack_by_country(context: AssetExecutionContext, silver: int) -> Output[int]:
    """Run dbt Gold attack by country model. Returns row count."""
    context.log.info("Running dbt Gold attack_volume_by_country model")

    result = subprocess.run(
        [
            "dbt", "run",
            "--select", "attack_volume_by_country",
            "--project-dir", "dbt_project",
            "--profiles-dir", "dbt_project",
            "--target", "dev",
        ],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        context.log.error(f"dbt Gold attack_by_country run failed: {result.stderr}")
        raise RuntimeError(f"dbt Gold attack_volume_by_country model failed: {result.stderr}")

    # Count rows
    import duckdb

    conn = duckdb.connect("data/security_analytics.duckdb", read_only=True)
    try:
        row = conn.execute(
            "SELECT COUNT(*) FROM security_analytics.attack_volume_by_country"
        ).fetchone()
        row_count = row[0] if row else 0
    except Exception:
        row_count = 0
    finally:
        conn.close()

    return Output(
        row_count,
        metadata={"row_count": MetadataValue.int(row_count)},
    )


@asset(
    ins={"silver": AssetIn("silver_events")},
    description="Gold hourly event summary aggregation",
    group_name="analytics",
    metadata={
        "table": "hourly_event_summary",
        "layer": "gold",
    },
)
def gold_hourly_summary(context: AssetExecutionContext, silver: int) -> Output[int]:
    """Run dbt Gold hourly event summary model. Returns row count."""
    context.log.info("Running dbt Gold hourly_event_summary model")

    result = subprocess.run(
        [
            "dbt", "run",
            "--select", "hourly_event_summary",
            "--project-dir", "dbt_project",
            "--profiles-dir", "dbt_project",
            "--target", "dev",
        ],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        context.log.error(f"dbt Gold hourly_summary run failed: {result.stderr}")
        raise RuntimeError(f"dbt Gold hourly_event_summary model failed: {result.stderr}")

    # Count rows
    import duckdb

    conn = duckdb.connect("data/security_analytics.duckdb", read_only=True)
    try:
        row = conn.execute(
            "SELECT COUNT(*) FROM security_analytics.hourly_event_summary"
        ).fetchone()
        row_count = row[0] if row else 0
    except Exception:
        row_count = 0
    finally:
        conn.close()

    return Output(
        row_count,
        metadata={"row_count": MetadataValue.int(row_count)},
    )


# ---------------------------------------------------------------------------
# ML Group
# ---------------------------------------------------------------------------


@asset(
    ins={"silver": AssetIn("silver_events")},
    description="Anomaly detection results from IsolationForest model",
    group_name="ml",
    metadata={
        "table": "anomaly_results",
        "layer": "gold",
        "model": "IsolationForest",
    },
)
def anomaly_results(context: AssetExecutionContext, silver: int) -> Output[int]:
    """Train model and score windows. Returns anomaly count.

    Runs the full ML pipeline: feature extraction, model training,
    prediction, and persistence of results.
    """
    context.log.info(f"Running anomaly detection pipeline (silver has {silver} records)")

    try:
        from ml_detection.features import extract_features
        from ml_detection.train import TrainingConfig, train_model
        from ml_detection.predict import persist_results, predict_anomalies

        db_path = Path("data/security_analytics.duckdb")

        # Extract features from hourly event summary
        features_df = extract_features(db_path)
        context.log.info(f"Extracted {len(features_df)} feature vectors")

        # Train model
        training_config = TrainingConfig()
        training_result = train_model(features_df, training_config)
        context.log.info(
            f"Model trained: {training_result.n_anomalies_detected} anomalies "
            f"({training_result.anomaly_percentage:.1f}%)"
        )

        # Predict anomalies
        prediction_result = predict_anomalies(features_df, training_result.model_path)
        context.log.info(
            f"Prediction complete: {prediction_result.n_anomalies} anomalies detected"
        )

        # Persist results
        rows_written = persist_results(
            prediction_result, db_path, training_result.model_version
        )

        return Output(
            prediction_result.n_anomalies,
            metadata={
                "anomalies_detected": MetadataValue.int(prediction_result.n_anomalies),
                "anomaly_percentage": MetadataValue.float(prediction_result.anomaly_percentage),
                "model_version": MetadataValue.text(training_result.model_version),
                "rows_written": MetadataValue.int(rows_written),
            },
        )

    except ImportError:
        # ML module not yet implemented - return placeholder
        context.log.warning(
            "ml_detection module not available. "
            "Anomaly detection will be available after Sprint 8."
        )
        return Output(
            0,
            metadata={
                "status": MetadataValue.text("skipped - ml_detection not implemented"),
            },
        )
    except Exception as e:
        context.log.error(f"Anomaly detection failed: {e}")
        raise
